package config

import (
	"go/format"
	"reflect"
	"sort"
	"strings"
)

// keyPathToIdent 把 YAML 键路径机械转换为 Go 标识符（导出名）。
// 规则：按 '.' 和 '_' 拆词，每词首字母大写后拼接。例如：
//
//	"ui.theme.name"                 -> "UiThemeName"
//	"features.quick_input.trigger_keys" -> "FeaturesQuickInputTriggerKeys"
//	"debug.log_level"               -> "DebugLogLevel"
//
// 不做 initialism 美化（Ui/Id 不转 UI/ID），换取无歧义、可机械逆推。
func keyPathToIdent(p string) string {
	parts := strings.FieldsFunc(p, func(r rune) bool { return r == '.' || r == '_' })
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}

// GenerateConfigKeyConsts 生成 configkey 包的源码内容（命名常量 = 键路径字符串）。
// 由 keypaths_test.go 的 TestExportKeyPaths -update 写出到
// pkg/config/configkey/keys_gen.go，作为键路径字符串的单一权威来源，
// 供调用方以编译期可校验的常量替代裸字符串。
func GenerateConfigKeyConsts() string {
	var b strings.Builder
	b.WriteString("// Code generated by \"go test ./pkg/config -run TestExportKeyPaths -update\"; DO NOT EDIT.\n\n")
	b.WriteString("// Package configkey 提供配置 YAML 键路径的命名常量，由 Config 结构体 yaml tag\n")
	b.WriteString("// 反射生成，是键路径字符串的单一权威来源。调用方应引用本包常量而非裸字符串，\n")
	b.WriteString("// 避免键路径写错/重构后漂移（历史上 config.set/toggle 曾因此出过 bug）。\n")
	b.WriteString("package configkey\n\n")
	b.WriteString("const (\n")
	for _, p := range AllKeyPaths() {
		b.WriteString("\t")
		b.WriteString(keyPathToIdent(p))
		b.WriteString(" = \"")
		b.WriteString(p)
		b.WriteString("\"\n")
	}
	b.WriteString(")\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		// 理论上不会发生（生成的是合法 Go 源码）；退化为未格式化输出便于排查。
		return b.String()
	}
	return string(formatted)
}

// AllKeyPaths 反射遍历 Config 的 yaml tag 树，返回全量 v1 配置键点路径
// （叶子字段；嵌套 struct 展开，slice/map 字段记为叶子节点）。
// 用途：导出给设置前端做 key 一致性校验（设计 §7.2——前端 schema/搜索索引
// 中出现的 key 必须 ∈ 本清单，拼写漂移在 CI 一次性抓出），
// 由 keypaths_test.go 的 TestExportKeyPaths -update 写出 JSON。
func AllKeyPaths() []string {
	var out []string
	collectKeyPaths(reflect.TypeOf(Config{}), "", &out)
	sort.Strings(out)
	return out
}

func collectKeyPaths(t reflect.Type, prefix string, out *[]string) {
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		tag := strings.Split(f.Tag.Get("yaml"), ",")[0]
		if tag == "" || tag == "-" {
			continue
		}
		p := tag
		if prefix != "" {
			p = prefix + "." + tag
		}
		if f.Type.Kind() == reflect.Struct {
			collectKeyPaths(f.Type, p, out)
			continue
		}
		*out = append(*out, p)
	}
}
